### ISSUE TITLE
Is it calculating remaining searches correctly?

### ISSUE THREAD

**Issue by AnthonyBe** [zengfu94/MicrosoftRewards#20]
Found accounts.txt
sleeping for 332 seconds
sleeping for 1714 seconds
sleeping for 1198 seconds
accountremoved@domainremoved: logging in
accountremoved@domainremoved: current points: 11927
accountremoved@domainremoved: desktop left: 0
accountremoved@domainremoved: mobile left: 3
accountremoved@domainremoved: next search in: 549 seconds

When I logged into Rewards website:
PC Search 90 of 90 points (good, script is correct)
Mobile Search 42 of 60 points

The script said 3 mobile searches left, but shouldn't it have been 6 to get maximum points?

**Comment by zengfu94** [comment]
Ah script calculates in multiples of 5 (us number). I guess ill have to add that to locale portion. Thanks

**Comment by AnthonyBe** [comment]
US gets 5 points per search?!?! Sheesh :)
I hadn't realised that they change the earning potential by locale.
Mine shows as 3 points per Bing Search and then the only other factor is if you are Level 1 you can earn a max of 30 points per day, and if you are Level 2 you can earn 150 points per day.

**Comment by AnthonyBe** [comment]
This issue does not appear to be resolved for me.
Using commit cdf2961
In common.py made following changes to default:
selectedLocale = "Australia"
querytime_low = 2000
querytime_high = 3000

Script execution:
accountremoved@domainremoved: logging in
accountremoved@domainremoved: current points: 12525
accountremoved@domainremoved: searches done

When I logged into Rewards website:
12,525 Available points (good, website and script match so I'm not seeing any website latency)
PC Search 78 of 90 points
Mobile Search 60 of 60 points

Script should've determined that I needed 4 desktop searches (based on each search generating 3 points in Australia)

**Comment by zengfu94** [comment]
If you go to https://bing.com/rewardsapp/flyoutpage?style=v2 what do the PC search and mobile searches progresses say?

**Comment by AnthonyBe** [comment]
When I click across to PC searches on the flyout URL it *does* say PC Searches are at 90 of 90 while the main website continues to say 78 of 90 points.

Hmm.. OK doesn't help, 

I'm guessing the flyout data is more trustworthy than the main website?

**Comment by zengfu94** [comment]
No I just wanted to confirm my suspicions, main flyout is bad and not updating so I'm having to refactor a few things.

**Comment by zengfu94** [comment]
@AnthonyBe git pull and test, all my accounts passed initial tests.

**Comment by AnthonyBe** [comment]
Testing Commit ee2d175 
Result = worse

accountremoved@domainremoved: logging in
accountremoved@domainremoved: current points: 12615
accountremoved@domainremoved: desktop left: 30
accountremoved@domainremoved: mobile left: 20

It seems to have not determined how many points I have and has just gone for max. searches.

Main flyout is still saying:
PC Search 78 of 90 points
Mobile Search 60 of 60 points

https://bing.com/rewardsapp/flyoutpage?style=v2  is saying
PC Search 90 of 90 points
Mobile Search 60 of 60 points

**Comment by zengfu94** [comment]
Check https://bing.com/bepflyoutpage?style=modular

**Comment by AnthonyBe** [comment]
I get a Page not Found on that URL - https://www.bing.com/bepflyoutpage?style=modular

**Comment by zengfu94** [comment]
Crud https://bing.com/rewardsapp/bepflyoutpage?style=modular

**Comment by AnthonyBe** [comment]
Hmmm... I think I'm getting some weird cookie issues.. or MSFT are having inconsistencies.. sometimes that URL (as well as the main Rewards flyout and the Edge Extension) say that I'm in an unsupported market and Bing Rewards is only open in the US (which in itself is not accurate.. /sigh). I get the same inconsistency in Chrome as well.

But sometimes is works fine, in which case I get:
78/90 PC SEARCH
60/60 MOBILE SEARCH

I guess the problem is if I get a 'unsupported market' response (which does redirect to https://www.bing.com/rewards/unsupportedmarket) then the script is not handling correctly and doing max. searches?

**Comment by AnthonyBe** [comment]
Tested a few more times with multiple accounts. Same issue. Seems to be just giving me max. searches.

**Comment by zengfu94** [comment]
This should be fixed in latest, forgot I hadn't added the subtract currently done from total :)

**Comment by AnthonyBe** [comment]
Running  commit 692e1a3 
Still doesn't look right.
All of my accounts today when first logged in showed:
Desktop left: 30
Mobile lift: 0
